version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # AMQP protocol
      - "15672:15672"     # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  api-gateway:
    build: ../api-gateway
    depends_on:
      - rabbitmq
    ports:
    - "3001:3001"

  user-service:
    build: ../user-service
    depends_on:
      - rabbitmq

  user-db:
    image: postgres
    container_name: user-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: app-owner
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data: {}
  user_data: {}